lib: list: implement `insert`

diff --git a/lib/list b/lib/list
--- a/lib/list
+++ b/lib/list
@@ -25,21 +25,34 @@ class List       \
   _pretty_print  \
   _remove        \
 
+check_index_within_range() {
+  # 1 -> index
+  # 2 -> length
+  if [ -z "$1" ] ||
+     [ "$1" -ge "$2" ] ||
+     [ "$1" -le -"$2" ]
+  then
+    printf 'Invalid index: %s\n' "$1"
+    return 1
+  fi >&2
+}
+
 List_create_node() {
   # create a unique name
-  node_name=List_"$name"_"$created_count_"
+  new_node=List_"$name"_"$created_count_"
   "$self"_created_count__is "$((created_count_ + 1))"
-  Node "$node_name" "$1" "$2"
+  Node "$new_node" "$1" "$2"
 }
 
 List_append() {
+  local new_node
   "$self"_create_node "$1"
   if [ "$length_" -eq 0 ]; then
-    "$self"_head__is "$node_name"
+    "$self"_head__is "$new_node"
   else
-    "$tail_"_next_is "$node_name"
+    "$tail_"_next_is "$new_node"
   fi
-  "$self"_tail__is "$node_name"
+  "$self"_tail__is "$new_node"
   "$self"_length__is "$((length_ + 1))"
 }
 
@@ -59,13 +72,7 @@ List_index() {
 }
 
 List_get() {
-  if [ -z "$1" ] ||
-     [ "$1" -ge "$length_" ] ||
-     [ "$(($1 * -1))" -ge "$length_" ]
-  then
-    printf 'Invalid index: %s\n' "$1"
-    return 1
-  fi >&2
+  check_index_within_range "$1" "$length_" || return
 
   if [ "$1" -lt 0 ]; then
     target_index="$((length_ + $1))"
@@ -85,6 +92,8 @@ List_get() {
 }
 
 List_pretty_print() {
+  printf '== %s == (length: %s, head: %s, tail: %s)
+' "$self" "$length_" "$("$head_"_value)" "$("$tail_"_value)"
   index=0
   node="$head_"
   while [ "$index" -lt "$length_" ]; do
@@ -109,6 +118,7 @@ List_remove() {
       else
         "$prev"_next_is "$("$node"_next)"
       fi
+      # FIXME also delete object when supported by clash
       "$self"_length__is "$((length_ - 1))"
       return
     fi
@@ -129,7 +139,26 @@ List_clear() {
 }
 
 List_insert() {
-  :
+  check_index_within_range "$1" "$length_" || return
+  index=0
+  node="$head_"
+  prev=
+  while [ "$index" -lt "$1" ]; do
+    prev="$node"
+    node="$("$node"_next)"
+    index="$((index + 1))"
+  done
+  local new_node
+  "$self"_create_node "$2" "$node"
+  if [ -n "$prev" ]; then
+    "$prev"_next_is "$new_node"
+  fi
+  if [ "$prev" = "$tail_" ]; then
+    "$self"_tail__is "$new_node"
+  elif [ "$node" = "$head_" ]; then
+    "$self"_head__is "$new_node"
+  fi
+  "$self"_length__is "$((length_ + 1))"
 }
 
 _List() {
